### ISSUE TITLE
2024-02-15: Thursday February 15 2024

### ISSUE THREAD

**Issue by Shelrothman** [Shelrothman/planner#4]
### Priorities

1. Follow ups to calls
2. Work on admin api

### To-Do List

- [x] review and add notes to the versioning figma-jam
- [x] review and grok the proposal for the wf's
- [x] review what Kristin spoke about in meeting
- [x] complete the configuration for the new admin-api repo
