### ISSUE TITLE
2024-02-22: Thursday February 22 2024

### ISSUE THREAD

**Issue by Shelrothman** [Shelrothman/planner#5]
### Priorities

1. Research/Implementation Efficacy Calculations
2. Enter Goals
3. Research the error handeling
4. ci/cd

### To-Do List

- [ ] Begin the Dev work of the us
- [ ] Review the ui PR
- [ ] Do the temp tools goals
- [ ] look into the error handling in root tool
