### ISSUE TITLE
2024-03-06: Wednesday March 6 2024

### ISSUE THREAD

**Issue by Shelrothman** [Shelrothman/planner#7]
### Priorities

1. at Refactor/Fix
2. Docs
3. 

### To-Do List

- [ ] look into the doc overwrites,
- [ ] work on the portal
- [ ] go to stores
